services:
  api:
    build: .
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "./images:/app/images"
    ports:
      - "5000:5000"
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fingerprints
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
