version: '3.8'

services:
  api:
    build: .
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/sys/bus/usb:/sys/bus/usb"
      - "./images:/app/images"
    ports:
      - "5500:5500"
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    restart: unless-stopped
    # Ejecutar como root para permisos USB
    user: "0:0"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fingerprints
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
