services:
  api:
    build: .
    volumes:
      - /dev:/dev
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - UDEV=1
      - MONGODB_URI=mongodb://localhost:27017/fingerprints
    network_mode: host
    restart: unless-stopped
