services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /dev:/dev
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - UDEV=1
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fingerprints
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
