class SGFDxErrorCode:
    SGFDX_ERROR_NONE = 0
    SGFDX_ERROR_CREATION_FAILED = 1
    SGFDX_ERROR_FUNCTION_FAILED = 2
    SGFDX_ERROR_INVALID_PARAM = 3
    SGFDX_ERROR_NOT_USED = 4
    SGFDX_ERROR_DLLLOAD_FAILED = 5
    SGFDX_ERROR_DLLLOAD_FAILED_DRV = 6
    SGFDX_ERROR_DLLLOAD_FAILED_ALGO = 7 